select * from SNOWFLAKE.TELEMETRY.EVENTS;

PUT file:////Users/liza.wu/Downloads/docebo_location.csv @TRAINING.INGESTION.DEV_S3_INBOUND_STAGE;

CREATE OR REPLACE FILE FORMAT TRAINING.INGESTION.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

SELECT *
FROM TABLE(
  INFER_SCHEMA(
    LOCATION=>'@DEV_INTERNAL_STAGE',
    FILE_FORMAT=>'TRAINING.INGESTION.CSV_FORMAT'
    )
  );

CREATE OR REPLACE STAGE TRAINING.INGESTION.DEV_INTERNAL_STAGE;

PUT file:///Users/liza.wu/Downloads/docebo_classroom.csv @TRAINING.INGESTION.DEV_INTERNAL_STAGE;

DESC USER EMULE2026;